name: flutter_circular_chart
description: Animated radial and pie charts for Flutter
version: 0.2.1
author: Victor Choueiri <victor.oc@gmail.com>
homepage: https://github.com/xqwzts/flutter_circular_chart

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: '>=3.1.2 <4.0.0'
